import Mathlib.Analysis.Analytic.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.LinearAlgebra.GeneralLinearGroup.Basic
import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.Polynomial.Degree.Defs
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Ring

/-!
# Finite-dimensional translation spaces

For a continuous function `f : ℝ → ℝ`, the note considers the span of the translates
`x ↦ f (x + a)`.  The elementary translation-space construction and its action are in
the shared translation definitions below.

The analytic and exponential-polynomial classification is recorded below as an explicit interface.
Mathlib currently does not provide the needed theorem which turns a continuous finite-dimensional
translation representation of `ℝ` into a matrix exponential and then into its complex Jordan
decomposition.  The matrix-coefficient part, which only uses the translation action itself, is
proved here.
-/

open scoped BigOperators

namespace FiniteDimensionalTranslation

namespace RealTranslation

/-- Translation by `a` for functions on the additive real line. -/
def translate (a : ℝ) (h : ℝ → ℝ) : ℝ → ℝ :=
  fun x ↦ h (x + a)

@[simp]
theorem translate_zero (h : ℝ → ℝ) : translate 0 h = h := by
  funext x
  simp [translate]

theorem translate_comp (a b : ℝ) (h : ℝ → ℝ) :
    translate a (translate b h) = translate (a + b) h := by
  funext x
  simp [translate, add_assoc]

theorem translate_map_add (a : ℝ) (h₁ h₂ : ℝ → ℝ) :
    translate a (h₁ + h₂) = translate a h₁ + translate a h₂ := by
  funext x
  simp [translate]

theorem translate_map_smul (a c : ℝ) (h : ℝ → ℝ) :
    translate a (c • h) = c • translate a h := by
  funext x
  simp [translate]

/-- The translation space generated by all real translates of `f`. -/
def translationSpan (f : ℝ → ℝ) : Submodule ℝ (ℝ → ℝ) :=
  Submodule.span ℝ (Set.range (fun a : ℝ ↦ translate a f))

theorem mem_translationSpan (f : ℝ → ℝ) (a : ℝ) :
    translate a f ∈ translationSpan f :=
  Submodule.subset_span ⟨a, rfl⟩

theorem f_mem_translationSpan (f : ℝ → ℝ) : f ∈ translationSpan f := by
  simpa using mem_translationSpan f 0

/-- Every translate preserves the translation space. -/
theorem translate_mem_translationSpan {f h : ℝ → ℝ} (a : ℝ)
    (hh : h ∈ translationSpan f) : translate a h ∈ translationSpan f := by
  induction hh using Submodule.span_induction with
  | mem h hh =>
      rcases hh with ⟨b, rfl⟩
      rw [translate_comp]
      exact mem_translationSpan f (a + b)
  | zero =>
      simpa [translate] using (translationSpan f).zero_mem
  | add h₁ h₂ _ _ ih₁ ih₂ =>
      simpa [translate_map_add] using (translationSpan f).add_mem ih₁ ih₂
  | smul c h _ ih =>
      simpa [translate_map_smul] using (translationSpan f).smul_mem c ih

/-- The restriction of a translation to the translation space. -/
def translationOperator (f : ℝ → ℝ) (a : ℝ) :
    translationSpan f →ₗ[ℝ] translationSpan f where
  toFun h := ⟨translate a h, translate_mem_translationSpan a h.property⟩
  map_add' h₁ h₂ := by
    apply Subtype.ext
    exact translate_map_add a h₁ h₂
  map_smul' c h := by
    apply Subtype.ext
    exact translate_map_smul a c h

@[simp]
theorem translationOperator_zero (f : ℝ → ℝ) :
    translationOperator f 0 = LinearMap.id := by
  ext h
  apply Subtype.ext
  simp [translationOperator]

theorem translationOperator_add (f : ℝ → ℝ) (a b : ℝ) :
    translationOperator f (a + b) =
      (translationOperator f a).comp (translationOperator f b) := by
  ext h
  apply Subtype.ext
  exact (translate_comp a b h).symm

/-- Translation by `a` as a linear equivalence, with inverse translation by `-a`. -/
def translationEquiv (f : ℝ → ℝ) (a : ℝ) :
    translationSpan f ≃ₗ[ℝ] translationSpan f where
  toFun := translationOperator f a
  invFun := translationOperator f (-a)
  left_inv h := by
    apply Subtype.ext
    simp [translationOperator, translate, add_assoc]
  right_inv h := by
    apply Subtype.ext
    simp [translationOperator, translate, add_assoc]
  map_add' := (translationOperator f a).map_add
  map_smul' := (translationOperator f a).map_smul

theorem translationEquiv_zero (f : ℝ → ℝ) :
    translationEquiv f 0 = LinearEquiv.refl ℝ (translationSpan f) := by
  ext h
  apply Subtype.ext
  simp [translationEquiv, translationOperator]

theorem translationEquiv_add (f : ℝ → ℝ) (a b : ℝ) :
    translationEquiv f (a + b) =
      translationEquiv f a * translationEquiv f b := by
  ext h
  apply Subtype.ext
  exact (translate_comp a b h).symm

/-!
The translations as a subgroup of the general linear group.
-/

def translationGLHom (f : ℝ → ℝ) :
    Multiplicative ℝ →* LinearMap.GeneralLinearGroup ℝ (translationSpan f) where
  toFun a :=
    LinearMap.GeneralLinearGroup.ofLinearEquiv (translationEquiv f a.toAdd)
  map_one' := by
    rw [show (1 : Multiplicative ℝ).toAdd = 0 by rfl, translationEquiv_zero]
    rfl
  map_mul' a b := by
    rw [show (a * b).toAdd = a.toAdd + b.toAdd by rfl, translationEquiv_add]
    rfl

end RealTranslation

open RealTranslation

abbrev TranslationSpace (f : ℝ → ℝ) := translationSpan f

/-- Evaluation at the origin on the translation space. -/
def evaluationAtZero (f : ℝ → ℝ) : TranslationSpace f →ₗ[ℝ] ℝ where
  toFun h := h 0
  map_add' h₁ h₂ := by simp
  map_smul' c h := by simp

@[simp]
theorem evaluationAtZero_apply (f : ℝ → ℝ) (h : TranslationSpace f) :
    evaluationAtZero f h = h 0 := rfl

/-- The distinguished vector in the translation space is the original function. -/
def distinguishedVector (f : ℝ → ℝ) : TranslationSpace f :=
  ⟨f, f_mem_translationSpan f⟩

@[simp]
theorem evaluationAtZero_distinguishedVector (f : ℝ → ℝ) :
    evaluationAtZero f (distinguishedVector f) = f 0 := rfl

/-- Evaluation at the origin after translating by `a` evaluates the original function at `a`. -/
theorem evaluationAtZero_translation (f : ℝ → ℝ) (a : ℝ) :
    evaluationAtZero f (translationOperator f a (distinguishedVector f)) = f a := by
  simp [evaluationAtZero, distinguishedVector, translationOperator, translate]

/-- The translation action packaged as a subgroup of `GL` of the translation space. -/
abbrev translationSubgroup (f : ℝ → ℝ) :=
  Multiplicative ℝ →* LinearMap.GeneralLinearGroup ℝ (TranslationSpace f)

/-- A scalar matrix coefficient of the real translation subgroup. -/
def IsTranslationMatrixCoefficient (f : ℝ → ℝ) : Prop :=
  ∃ ρ : translationSubgroup f,
    ∃ ell : TranslationSpace f →ₗ[ℝ] ℝ,
      ∃ v : TranslationSpace f,
        ∀ x : ℝ,
          f x = ell (LinearMap.GeneralLinearGroup.toLinearEquiv
            (ρ (Multiplicative.ofAdd x)) v)

theorem isTranslationMatrixCoefficient (f : ℝ → ℝ) :
    IsTranslationMatrixCoefficient f := by
  refine ⟨translationGLHom f, evaluationAtZero f, distinguishedVector f, ?_⟩
  intro x
  simpa [translationGLHom] using (evaluationAtZero_translation f x).symm

/-!
The next structure is the missing analytic/spectral theorem.  It is intentionally an interface:
the conclusions are not silently assumed to be available from Mathlib.
-/

structure SpectralClassification (f : ℝ → ℝ) (hf : Continuous f)
    [FiniteDimensional ℝ (TranslationSpace f)] : Prop where
  /-- The finite-dimensional translation space forces real analyticity. -/
  analytic : AnalyticOn ℝ f Set.univ
  /-- Complex exponential-polynomial decomposition with the dimension count. -/
  exists_exponential_polynomial :
    ∃ r : ℕ, ∃ λ : Fin r → ℂ, ∃ P : Fin r → Polynomial ℂ,
      Pairwise (fun i j ↦ λ i ≠ λ j) ∧
      (∀ j, P j ≠ 0) ∧
      (∀ x : ℝ,
        (f x : ℂ) = ∑ j, (P j).eval (x : ℂ) * Complex.exp (λ j * (x : ℂ))) ∧
      (∑ j, (P j).natDegree + 1) = Module.finrank ℝ (TranslationSpace f)

theorem exponential_polynomial_terms_le_dimension
    {f : ℝ → ℝ} [FiniteDimensional ℝ (TranslationSpace f)]
    (hf : Continuous f) (C : SpectralClassification f hf) :
    ∃ r : ℕ, ∃ λ : Fin r → ℂ, ∃ P : Fin r → Polynomial ℂ,
      Pairwise (fun i j ↦ λ i ≠ λ j) ∧
      (∀ j, P j ≠ 0) ∧
      (∀ x : ℝ,
        (f x : ℂ) = ∑ j, (P j).eval (x : ℂ) * Complex.exp (λ j * (x : ℂ))) ∧
      (∑ j, (P j).natDegree + 1) = Module.finrank ℝ (TranslationSpace f) ∧
      r ≤ Module.finrank ℝ (TranslationSpace f) := by
  rcases C.exists_exponential_polynomial with
    ⟨r, λ, P, hλ, hP, hformula, hdimension⟩
  refine ⟨r, λ, P, hλ, hP, hformula, hdimension, ?_⟩
  calc
    r = ∑ _j : Fin r, 1 := by simp
    _ ≤ ∑ j : Fin r, (P j).natDegree + 1 := by
      apply Finset.sum_le_sum
      intro j hj
      exact Nat.succ_le_succ (Nat.zero_le _)
    _ = Module.finrank ℝ (TranslationSpace f) := hdimension

/-- The formal version of the finite-dimensional translation-space theorem, conditional on the
spectral interface above. -/
theorem finiteDimensionalTranslationSpace
    (f : ℝ → ℝ) (hf : Continuous f)
    [FiniteDimensional ℝ (TranslationSpace f)]
    (C : SpectralClassification f hf) :
    AnalyticOn ℝ f Set.univ ∧
      (∃ r : ℕ, ∃ λ : Fin r → ℂ, ∃ P : Fin r → Polynomial ℂ,
        Pairwise (fun i j ↦ λ i ≠ λ j) ∧
        (∀ j, P j ≠ 0) ∧
        (∀ x : ℝ,
          (f x : ℂ) = ∑ j, (P j).eval (x : ℂ) * Complex.exp (λ j * (x : ℂ))) ∧
        (∑ j, (P j).natDegree + 1) = Module.finrank ℝ (TranslationSpace f) ∧
        r ≤ Module.finrank ℝ (TranslationSpace f)) ∧
      IsTranslationMatrixCoefficient f := by
  refine ⟨C.analytic, ?_, isTranslationMatrixCoefficient f⟩
  exact exponential_polynomial_terms_le_dimension hf C

/-! The functional-equation application. -/

/-- The addition law used to reduce the translation space to two generators. -/
def AdditionLaw (f g : ℝ → ℝ) : Prop :=
  ∀ x y : ℝ, f (x + y) = f x * g y + f y * g x

theorem translationSpan_le_two_of_additionLaw
    {f g : ℝ → ℝ}
    (hadd : AdditionLaw f g) :
    translationSpan f ≤ Submodule.span ℝ ({f, g} : Set (ℝ → ℝ)) := by
  apply Submodule.span_le.2
  rintro _ ⟨a, rfl⟩
  have htranslate : translate a f = g a • f + f a • g := by
    funext x
    simpa [translate, mul_comm] using hadd x a
  rw [htranslate]
  exact (Submodule.span ℝ ({f, g} : Set (ℝ → ℝ))).add_mem
    ((Submodule.span ℝ ({f, g} : Set (ℝ → ℝ))).smul_mem _
      (Submodule.subset_span (by simp)))
    ((Submodule.span ℝ ({f, g} : Set (ℝ → ℝ))).smul_mem _
      (Submodule.subset_span (by simp)))

/-- The functional equation in the opening example of the note. -/
def SineProductEquation (f : ℝ → ℝ) : Prop :=
  ∀ x y : ℝ, f (x + y) * f (x - y) = f x ^ 2 - f y ^ 2

/-- The auxiliary function used in the standard reduction of the functional equation. -/
def auxiliaryFunction (f : ℝ → ℝ) (a : ℝ) : ℝ → ℝ :=
  (2 * f a)⁻¹ • (translate a f - translate (-a) f)

@[simp]
theorem auxiliaryFunction_apply (f : ℝ → ℝ) (a x : ℝ) :
    auxiliaryFunction f a x =
      (f (x + a) - f (x - a)) / (2 * f a) := by
  simp [auxiliaryFunction, translate, div_eq_mul_inv, sub_eq_add_neg, mul_comm]

theorem auxiliaryFunction_mem_translationSpan (f : ℝ → ℝ) (a : ℝ) :
    auxiliaryFunction f a ∈ translationSpan f := by
  simpa [auxiliaryFunction] using
    (translationSpan f).smul_mem (2 * f a)⁻¹
      ((translationSpan f).sub_mem (mem_translationSpan f a)
        (mem_translationSpan f (-a)))

/-- The two displayed translation identities imply the addition law. -/
theorem additionLaw_of_translationIdentities
    {f g : ℝ → ℝ}
    (hsum : ∀ x y : ℝ, f (x + y) + f (x - y) = 2 * f x * g y)
    (hdiff : ∀ x y : ℝ, f (x + y) - f (x - y) = 2 * f y * g x) :
    AdditionLaw f g := by
  intro x y
  calc
    f (x + y) =
        ((f (x + y) + f (x - y)) + (f (x + y) - f (x - y))) / 2 := by ring
    _ = (2 * f x * g y + 2 * f y * g x) / 2 := by rw [hsum, hdiff]
    _ = f x * g y + f y * g x := by ring

theorem translationSpan_le_two_of_auxiliaryAdditionLaw
    {f : ℝ → ℝ} (a : ℝ)
    (hadd : AdditionLaw f (auxiliaryFunction f a)) :
    translationSpan f ≤
      Submodule.span ℝ ({f, auxiliaryFunction f a} : Set (ℝ → ℝ)) :=
  translationSpan_le_two_of_additionLaw hadd

theorem finiteDimensional_translationSpan_of_additionLaw
    {f g : ℝ → ℝ} (hadd : AdditionLaw f g) :
    FiniteDimensional ℝ (translationSpan f) := by
  classical
  let W : Submodule ℝ (ℝ → ℝ) := Submodule.span ℝ ({f, g} : Set (ℝ → ℝ))
  have hW : FiniteDimensional ℝ W := by
    dsimp [W]
    apply FiniteDimensional.span_of_finite
    simp
  letI : FiniteDimensional ℝ W := hW
  exact Submodule.finiteDimensional_of_le
    (show translationSpan f ≤ W from
      translationSpan_le_two_of_additionLaw hadd)

theorem finrank_translationSpan_le_two_of_additionLaw
    {f g : ℝ → ℝ} (hadd : AdditionLaw f g) :
    Module.finrank ℝ (translationSpan f) ≤ 2 := by
  classical
  let W : Submodule ℝ (ℝ → ℝ) := Submodule.span ℝ ({f, g} : Set (ℝ → ℝ))
  have hW : FiniteDimensional ℝ W := by
    dsimp [W]
    apply FiniteDimensional.span_of_finite
    simp
  letI : FiniteDimensional ℝ W := hW
  have hle : translationSpan f ≤ W := by
    exact translationSpan_le_two_of_additionLaw hadd
  calc
    Module.finrank ℝ (translationSpan f) ≤ Module.finrank ℝ W :=
      Submodule.finrank_mono hle
    _ ≤ (({f, g} : Set (ℝ → ℝ)).toFinset.card) := by
      simpa [W] using
        (finrank_span_le_card (R := ℝ) (M := ℝ → ℝ)
          ({f, g} : Set (ℝ → ℝ)))
    _ ≤ 2 := by simp

/-!
The omitted step from the original functional equation to the two translation identities is
isolated in the following interface.  Once supplied, the dimension bound is completely formal.
-/
structure SineProductAuxiliaryReduction : Prop where
  identities : ∀ {f : ℝ → ℝ}, Continuous f → SineProductEquation f →
    ∃ a : ℝ, f a ≠ 0 ∧
      (∀ x y : ℝ,
        f (x + y) + f (x - y) = 2 * f x * auxiliaryFunction f a y) ∧
      (∀ x y : ℝ,
        f (x + y) - f (x - y) = 2 * f y * auxiliaryFunction f a x)

theorem finrank_translationSpan_le_two_of_sineProduct
    (R : SineProductAuxiliaryReduction) {f : ℝ → ℝ}
    (hf : Continuous f) (hEquation : SineProductEquation f) :
    Module.finrank ℝ (translationSpan f) ≤ 2 := by
  rcases R.identities hf hEquation with ⟨a, _, hsum, hdiff⟩
  exact finrank_translationSpan_le_two_of_additionLaw
    (additionLaw_of_translationIdentities hsum hdiff)

/-- The three families of solutions recorded at the end of the note. -/
def SineProductSolutions (f : ℝ → ℝ) : Prop :=
  (∃ c : ℝ, f = fun x ↦ c * x) ∨
    (∃ A ω : ℝ, f = fun x ↦ A * Real.sin (ω * x)) ∨
    (∃ A k : ℝ, f = fun x ↦ A * Real.sinh (k * x))

/-!
The derivation of the two translation identities from `SineProductEquation`, and the final
substitution into the exponential-polynomial forms, are not theorems supplied by Mathlib.  They
are therefore left as an explicit interface rather than being asserted as completed proofs.
-/
structure SineProductSolutionClassification : Prop where
  classify : ∀ {f : ℝ → ℝ}, Continuous f → SineProductEquation f → SineProductSolutions f

end FiniteDimensionalTranslation
